### ISSUE TITLE
Blocks with block states currently not supported

### ISSUE THREAD

**Issue by vkamz597** [diamond-gold/DummyItemsBlocks#1]
Is the function currently scheduled?

**Version information**
PocketMine: 5.1.2
Plugin: 0.0.1
Minecraft: 1.20.0

**Comment by diamond-gold** [comment]
Blocks with block states is currently work in progress, it will be coming soon

**Comment by vkamz597** [comment]
Thanks.

**Comment by diamond-gold** [comment]
# Upcoming blocks
![image](https://github.com/diamond-gold/DummyItemsBlocks/assets/10301312/f9136fdc-6754-4fad-a99e-0f89c6fc51ea)

**Comment by roimee6** [comment]
> # Upcoming blocks
> ![image](https://user-images.githubusercontent.com/10301312/246717268-f9136fdc-6754-4fad-a99e-0f89c6fc51ea.png)

Can you mention me when you make a release?

**Comment by diamond-gold** [comment]
Subscribe to this issue and you will be notified when it is closed

**Comment by pandaa-be** [comment]
some updates?

**Comment by pandaa-be** [comment]
Thank you! :)

**Comment by diamond-gold** [comment]
Strange that the commit didn't close this issue...?
Anyways v1.0.0 is now released on poggit, all blocks and items up to 1.20 is now supported
