### ISSUE TITLE
Conflict with Customies / NetherReactor plugin

### ISSUE THREAD

**Issue by n00bslayr94** [diamond-gold/DummyItemsBlocks#18]
**Describe the bug**
Netherreactor + Customies plugin works fine in isolation. Add in dummy blocks, even though there are no overlapping blocks and suddenly pumpkins appear everywhere whenever you place or break a block. If you restart the server the pumpkins vanish but you get stuck inside them as they generate. 

**To Reproduce**
Add Customies, NetherReactor and DummyBlocks plugins and activate the nether reactor. 

**Expected behavior**
A spire of netherrack should form. Instead pumpkins and netherrack form. 

**Screenshots**

**Version information**
PocketMine: 5.10.0
Plugin: NetherReactor dev5, Mobplugin dev51, Customies (latest)
Minecraft: 1.20.50
![Minecraft 22_01_2024 21_31_49](https://github.com/diamond-gold/DummyItemsBlocks/assets/132199379/49853e26-d917-4621-90ba-77739ff8fe2b)
![image](https://github.com/diamond-gold/DummyItemsBlocks/assets/132199379/2fd2300f-9bcb-4eb0-849e-513ebd014b71)

**Comment by diamond-gold** [comment]
I am unable to reproduce this with Minecraft 1.20.51 PM 5.10.0
Customies v1.3.2, DummyItemsBlocks v1.0.3, MobPlugin dev-51, NetherReactor v0.0.1

It may be that you are using a proxy and proxies are known to cause this kind of issue with Customies
