### ISSUE TITLE
"Block observer is not supported" error

### ISSUE THREAD

**Issue by Wertzui123** [diamond-gold/DummyItemsBlocks#2]
I'm getting the error message `Block observer is not supported` when the plugin enables; from what I found in the code, it seems to be an issue with unmapped block states, but why is that? Is there any easy way to fix/workaround this? Thanks.

**Comment by Wertzui123** [comment]
By the way, it works when removing observers from the config, but I need them in order to load maps that use observers for decoration.

**Comment by diamond-gold** [comment]
The block state of observer block has changed, please wait for an update
https://github.com/pmmp/BedrockData/commit/f98bd1cae46d2920058acf3b23c0bedeac79f4ab#diff-50c52eb47a88ad337b5e5f468d02ddc489ef9e4b0cd4837596ed3f1258854abfR5502

**Comment by Wertzui123** [comment]
Seems to work, thank you for the quick fix!
