### ISSUE TITLE
Proxy!

### ISSUE THREAD

**Issue by GabBiswajit** [diamond-gold/DummyItemsBlocks#22]
I use This Plugin In My Server Which Is Run In Waterdog Proxy I Add This Plugin In My Lobby And Main Both Servers still it's make issue Like When I Go Lobby To Main Server Some Items Are Change Like Wood Look Like Stone ☠️ Cam You Slove This Issue?

**Comment by diamond-gold** [comment]
It may be that you are using Customies and proxies are known to cause this kind of issue with Customies

If you can reproduce the issue with only this plugin on the servers then I will investigate further
