### ISSUE TITLE
Incompatible with NetherGames fork

### ISSUE THREAD

**Issue by Kenilworth** [diamond-gold/DummyItemsBlocks#3]
What is this?

PocketMine-MP version: 5.3.3 [Protocol 594]
PHP version: 8.2.7
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: DummyItemsBlocks

_Error: Declaration of diamondgold\DummyItemsBlocks\tile\DummyTile::addAdditionalSpawnData(pocketmine\nbt\tag\CompoundTag $nbt): void must be compatible with pocketmine\block\tile\Spawnable::addAdditionalSpawnData(pocketmine\nbt\tag\CompoundTag $nbt, pocketmine\network\mcpe\convert\TypeConverter $typeConverter): void
File: plugins/DummyItemsBlocks/src/diamondgold/DummyItemsBlocks/tile/DummyTile
Line: 14
Type: E_COMPILE_ERROR_

**Comment by diamond-gold** [comment]
Are you using a fork of Pocketmine?

**Comment by Kenilworth** [comment]
nethergames

**Comment by diamond-gold** [comment]
Unfortunately it is not possible to support both PocketMine and the NetherGames fork at the same time.
