### ISSUE TITLE
Add minecraft:enchanted_book

### ISSUE THREAD

**Issue by justin-eckenweber** [diamond-gold/DummyItemsBlocks#4]
Can you add minecraft:enchanted_book? It would be useful because some of my players still have the book and I don't have a replacement for it atm.

**Comment by diamond-gold** [comment]
It has already been added

**Comment by justin-eckenweber** [comment]
Well it does not work then. It always says "no deserializer found for minecraft:enchanted_book". I can send you the full error later today.

**Comment by diamond-gold** [comment]
Check that you have it set in config.yml
https://github.com/diamond-gold/DummyItemsBlocks/blob/main/resources/config.yml#L167

**Comment by justin-eckenweber** [comment]
It doesn't even create the config.yml file... Well I'm using the version from poggit. That is weird. Or is it intended to be created yourself?

**Comment by diamond-gold** [comment]
It should be created automatically
