### ISSUE TITLE
minecraft:warped_nylium does not work

### ISSUE THREAD

**Issue by justin-eckenweber** [diamond-gold/DummyItemsBlocks#5]
```
2023-08-18 [06:34:48.395] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: XXXXXXX
2023-08-18 [06:34:48.396] [Server thread/CRITICAL]: pocketmine\data\SavedDataLoadingException: "No deserializer found for ID minecraft:warped_nylium" (EXCEPTION) in "pmsrc/src/item/Item" at line 723
```

**To Reproduce**
1. have an inventory with warped_nylium
2. join
3. crash

**Version information**
PocketMine: 5.4.2
Plugin: 1.0.1
Minecraft: latest

**Comment by diamond-gold** [comment]
Please check that you have it set in config.yml
https://github.com/diamond-gold/DummyItemsBlocks/blob/main/resources/config.yml#L107

**Comment by justin-eckenweber** [comment]
Yes, it is in the config.yml file.
I used INether before (in pm4) which implemented this block. Idk if it has something to do with it.

**Comment by justin-eckenweber** [comment]
Oh and can you add crying obsidian?
`pocketmine\data\bedrock\item\UnsupportedItemTypeException: "No deserializer found for ID minecraft:crying_obsidian" (EXCEPTION) in "pmsrc/src/data/bedrock/item/ItemDeserializer" at line 86`
This error appears right below

**Comment by justin-eckenweber** [comment]
<img width="451" alt="image" src="https://github.com/diamond-gold/DummyItemsBlocks/assets/39440218/f083e825-2381-44a1-b85a-7bb552bd0899">
I added it manually but I think it needs state support...

**Comment by diamond-gold** [comment]
Are you using a fork of pmmp?
Crying obsidian is already implemented by pmmp, adding it into config.yml should display the following warning:
`[Server thread/WARNING]: [DummyItemsBlocks] Block minecraft:crying_obsidian is already registered!`

**Comment by diamond-gold** [comment]
It does not seem like an issue with this plugin, reported to pmmp/PocketMine-MP#6008

**Comment by justin-eckenweber** [comment]
> Are you using a fork of pmmp?
> Crying obsidian is already implemented by pmmp, adding it into config.yml should display the following warning:
> `[Server thread/WARNING]: [DummyItemsBlocks] Block minecraft:crying_obsidian is already registered!`

No it is not a fork. Oh yeah and I see that message.

**Comment by justin-eckenweber** [comment]
> It does not seem like an issue with this plugin, reported to pmmp/PocketMine-MP#6008

Alright, thank you :)
