### ISSUE TITLE
Incompatible API version

### ISSUE THREAD

**Issue by ANDR0M3D41** [diamond-gold/DummyItemsBlocks#9]
I have a server with pocketmine 5.6.0, I installed the plugin and it shows this error and then the server shuts down.

Could not load plugin 'DummyItemsBlocks': Incompatible API version

![image](https://github.com/diamond-gold/DummyItemsBlocks/assets/111016658/6555836b-5645-4123-bb27-52813d3524cb)

Minecraft: 1.20.30
Plugin Version: 1.0.2

**Comment by diamond-gold** [comment]
There seems to be an issue with the poggit release phar, please use [dev build 18](https://poggit.pmmp.io/r/224207/DummyItemsBlocks_dev-18.phar) for now

**Comment by diamond-gold** [comment]
Fixed in v1.0.3
